//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphDigitizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphDigitizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1034{\fonttbl{\f0\fnil\fcharset0 Berlin Sans FB Demi;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green77\blue187;}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sl240\slmult1\qc\cf1\lang10\b\f0\fs32\par
        ///\fs48 Graph Digitizer\cf0\b0\f1\fs22\par
        ///\par
        ///\fs28 Current Version: 1.0\par
        ///Date: \ltrmark 14/\ltrmark 04/\ltrmark 2012\par
        ///\par
        ///\b Author:\par
        ///\b0 Fernando Andreu\par
        ///FernAndr@gmail.com\par
        ///}
        ///.
        /// </summary>
        internal static string HelpAbout {
            get {
                return ResourceManager.GetString("HelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1034{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sl240\slmult1\qj\lang10\b\f0\fs22 Basic program usage:\b0\par
        ///\pard{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-360\li720\sl240\slmult1\qj Load a graph with the first button of the above toolbar.\par
        ///{\pntext\f0 2.\tab}Select two points of the horizontal axis (X axis).\par
        ///{\pntext\f0 3.\tab}Select two points of the vertical axis ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpGeneral {
            get {
                return ResourceManager.GetString("HelpGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1034{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\lang10\f0\fs22 Press and hold the \b Left Control \b0 key over the main graph for enabling the \b precision mode\b0 .\par
        ///\par
        ///}
        ///.
        /// </summary>
        internal static string HelpKeys {
            get {
                return ResourceManager.GetString("HelpKeys", resourceCulture);
            }
        }
    }
}
